/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElCheckbox: typeof import('~icons/el/checkbox')['default']
    ElForm: typeof import('~icons/el/form')['default']
    ElFormItem: typeof import('~icons/el/form-item')['default']
    ElInput: typeof import('~icons/el/input')['default']
    ElTag: typeof import('~icons/el/tag')['default']
    Icon: typeof import('~icons/ic/on')['default']
    LayoutPageContent: typeof import('~icons/la/yout-page-content')['default']
    LayoutPageFooter: typeof import('~icons/la/yout-page-footer')['default']
    LayoutPageNavbar: typeof import('~icons/la/yout-page-navbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
